Add multiple device testing pipeline

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -2,23 +2,21 @@
 format_version: '8'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: ios
-trigger_map:
-- push_branch: "*"
-  workflow: pipeline_main
-- pull_request_source_branch: "*"
-  workflow: pipeline_main
-- tag: "*"
-  workflow: pipeline_main
 pipelines:
-  pipeline_all:
+  pipeline_multiple_shards:
     stages:
     - stage_1: {}
     - stage_2: {}
     - stage_3: {}
+  pipeline_multiple_devices:
+    stages:
+    - stage_1b: {}
+    - stage_2b: {}
+    - stage_3b: {}
 stages:
   stage_1:
     workflows:
-    - pipeline_main: {}
+    - pipeline_test_shards: {}
   stage_2:
     workflows:
     - tests_1: {}
@@ -27,6 +25,19 @@ stages:
     - tests_4: {}
     - tests_5: {}
   stage_3:
+    workflows:
+    - deploy: {}
+  stage_1b:
+    workflows:
+    - pipeline_multiple_destinations: {}
+  stage_2b:
+    workflows:
+    - test_iPhone_8: {}
+    - test_iPhone_8_plus: {}
+    - test_iPhone_11: {}
+    - test_iPhone_12: {}
+    - test_iPhone_13: {}
+  stage_3b:
     workflows:
     - deploy: {}
 workflows:
@@ -51,23 +62,12 @@ workflows:
             }\" > \\\n      \"${BITRISE_TEST_RESULT_DIR}/test_${i}/test-info.json\"\n\n
             \   ((i++))\n    \n  fi\ndone"
     - deploy-to-bitrise-io@2: {}
-  pipeline_main:
+  pipeline_multiple_destinations:
     steps:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@6: {}
     - cocoapods-install@2: {}
-    - git::https://github.com/DamienBitrise/bitrise-test-plan-sharder.git@master:
-        title: Bitrise Test Plan Sharder
-        inputs:
-        - xcode_project: Notes.xcodeproj
-        - target: NotesUITests
-        - shards: '5'
-        - scheme: Notes
-        - test_plan: Notes.xctestplan
-        - debug_mode: 'true'
-        - test_path: ''
-        - file_type: ".swift"
     - script@1.1:
         title: Build for Testing
         inputs:
@@ -100,15 +100,225 @@ workflows:
                 "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Notes_Notes_iphonesimulator13.5-x86_64.xctestrun" \
                 "$BITRISE_SOURCE_DIR/Notes.xcworkspace" \
                 "$BITRISE_SOURCE_DIR/Notes.xcodeproj" \
-                "$BITRISE_SOURCE_DIR/Notes.xctestplan" \
-                "$BITRISE_SOURCE_DIR/TestShard_0.xctestplan" \
-                "$BITRISE_SOURCE_DIR/TestShard_1.xctestplan" \
-                "$BITRISE_SOURCE_DIR/TestShard_2.xctestplan" \
-                "$BITRISE_SOURCE_DIR/TestShard_3.xctestplan" \
-                "$BITRISE_SOURCE_DIR/TestShard_4.xctestplan"
+                "$BITRISE_SOURCE_DIR/Notes.xctestplan"
     - deploy-to-bitrise-io@2:
         inputs:
         - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
+    before_run: []
+  test_iPhone_11:
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
+        title: Pull artifacts
+        inputs:
+        - verbose: true
+        - artifact_sources: stage_1.*
+    - script@1.1:
+        title: Unzip
+        inputs:
+        - content: |
+            set -euxo pipefail
+
+            echo "$BITRISE_ARTIFACT_PATHS"
+
+            echo "-- unzip -- "
+
+            exec unzip "${BITRISE_ARTIFACT_PATHS}"
+    - script@1.1:
+        title: Test without Building
+        inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
+            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\necho
+            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
+            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
+            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-parallel-testing-enabled
+            YES \\\n-maximum-parallel-testing-workers $SIMS \\\n-destination \"platform=iOS
+            Simulator,name=iPhone 11,OS=latest\" \\\n-retry-tests-on-failure \\\ntest-without-building\n\n"
+    - script@1.1:
+        title: Compress Result Bundle
+        is_always_run: true
+        inputs:
+        - content: |-
+            set -euxo pipefail
+            echo "-- compress --"
+
+            cd "${BITRISE_DEPLOY_DIR}/"
+
+            exec zip -qr \
+                "${BITRISE_DEPLOY_DIR}/TestResults3.zip" \
+                "/Users/vagrant/git/xcodebuild.xcresult"
+    - deploy-to-bitrise-io@2: {}
+    before_run: []
+  test_iPhone_12:
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
+        title: Pull artifacts
+        inputs:
+        - verbose: true
+        - artifact_sources: stage_1.*
+    - script@1.1:
+        title: Unzip
+        inputs:
+        - content: |
+            set -euxo pipefail
+
+            echo "$BITRISE_ARTIFACT_PATHS"
+
+            echo "-- unzip -- "
+
+            exec unzip "${BITRISE_ARTIFACT_PATHS}"
+    - script@1.1:
+        title: Test without Building
+        inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
+            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\necho
+            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
+            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
+            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-parallel-testing-enabled
+            YES \\\n-maximum-parallel-testing-workers $SIMS \\\n-destination \"platform=iOS
+            Simulator,name=iPhone 12,OS=latest\" \\\n-retry-tests-on-failure \\\ntest-without-building\n\n"
+    - script@1.1:
+        title: Compress Result Bundle
+        is_always_run: true
+        inputs:
+        - content: |-
+            set -euxo pipefail
+            echo "-- compress --"
+
+            cd "${BITRISE_DEPLOY_DIR}/"
+
+            exec zip -qr \
+                "${BITRISE_DEPLOY_DIR}/TestResults4.zip" \
+                "/Users/vagrant/git/xcodebuild.xcresult"
+    - deploy-to-bitrise-io@2: {}
+    before_run: []
+  test_iPhone_13:
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
+        title: Pull artifacts
+        inputs:
+        - verbose: true
+        - artifact_sources: stage_1.*
+    - script@1.1:
+        title: Unzip
+        inputs:
+        - content: |
+            set -euxo pipefail
+
+            echo "$BITRISE_ARTIFACT_PATHS"
+
+            echo "-- unzip -- "
+
+            exec unzip "${BITRISE_ARTIFACT_PATHS}"
+    - script@1.1:
+        title: Test without Building
+        inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
+            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\necho
+            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
+            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
+            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-parallel-testing-enabled
+            YES \\\n-maximum-parallel-testing-workers $SIMS \\\n-destination \"platform=iOS
+            Simulator,name=iPhone 13,OS=latest\" \\\n-retry-tests-on-failure \\\ntest-without-building\n\n"
+    - script@1.1:
+        title: Compress Result Bundle
+        is_always_run: true
+        inputs:
+        - content: |-
+            set -euxo pipefail
+            echo "-- compress --"
+
+            cd "${BITRISE_DEPLOY_DIR}/"
+
+            exec zip -qr \
+                "${BITRISE_DEPLOY_DIR}/TestResults5.zip" \
+                "/Users/vagrant/git/xcodebuild.xcresult"
+    - deploy-to-bitrise-io@2: {}
+    before_run: []
+  test_iPhone_8:
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
+        title: Pull artifacts
+        inputs:
+        - verbose: true
+        - artifact_sources: stage_1.*
+    - script@1.1:
+        title: Unzip
+        inputs:
+        - content: |
+            set -euxo pipefail
+
+            echo "$BITRISE_ARTIFACT_PATHS"
+
+            echo "-- unzip -- "
+
+            exec unzip "${BITRISE_ARTIFACT_PATHS}"
+    - script@1.1:
+        title: Test without Building
+        inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
+            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\necho
+            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
+            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
+            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-parallel-testing-enabled
+            YES \\\n-maximum-parallel-testing-workers $SIMS \\\n-destination \"platform=iOS
+            Simulator,name=iPhone 8,OS=latest\" \\\n-retry-tests-on-failure \\\ntest-without-building\n\n"
+    - script@1.1:
+        title: Compress Result Bundle
+        is_always_run: true
+        inputs:
+        - content: |-
+            set -euxo pipefail
+            echo "-- compress --"
+
+            cd "${BITRISE_DEPLOY_DIR}/"
+
+            exec zip -qr \
+                "${BITRISE_DEPLOY_DIR}/TestResults1.zip" \
+                "/Users/vagrant/git/xcodebuild.xcresult"
+    - deploy-to-bitrise-io@2: {}
+    before_run: []
+  test_iPhone_8_plus:
+    steps:
+    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
+        title: Pull artifacts
+        inputs:
+        - verbose: true
+        - artifact_sources: stage_1.*
+    - script@1.1:
+        title: Unzip
+        inputs:
+        - content: |
+            set -euxo pipefail
+
+            echo "$BITRISE_ARTIFACT_PATHS"
+
+            echo "-- unzip -- "
+
+            exec unzip "${BITRISE_ARTIFACT_PATHS}"
+    - script@1.1:
+        title: Test without Building
+        inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug
+            log\nset -x \n\nls -la\n\nmv ./Users/vagrant/git/* .\n\nls -la\n\necho
+            \"-- test-without-building --\"\n\nxcodebuild \\\n-workspace \"Notes.xcworkspace\"
+            \\\n-scheme \"Notes\" \\\n-sdk iphonesimulator \\\n-resultBundlePath \"xcodebuild.xcresult\"
+            \\\n-derivedDataPath \"/Users/vagrant/git/DerivedData\" \\\n-parallel-testing-enabled
+            YES \\\n-maximum-parallel-testing-workers $SIMS \\\n-destination \"platform=iOS
+            Simulator,name=iPhone 8 Plus,OS=latest\" \\\n-retry-tests-on-failure \\\ntest-without-building\n\n"
+    - script@1.1:
+        title: Compress Result Bundle
+        is_always_run: true
+        inputs:
+        - content: |-
+            set -euxo pipefail
+            echo "-- compress --"
+
+            cd "${BITRISE_DEPLOY_DIR}/"
+
+            exec zip -qr \
+                "${BITRISE_DEPLOY_DIR}/TestResults2.zip" \
+                "/Users/vagrant/git/xcodebuild.xcresult"
+    - deploy-to-bitrise-io@2: {}
     before_run: []
   tests_1:
     steps:
@@ -334,6 +544,65 @@ workflows:
                 "${BITRISE_DEPLOY_DIR}/TestResults5.zip" \
                 "/Users/vagrant/git/xcodebuild.xcresult"
     - deploy-to-bitrise-io@2: {}
+    before_run: []
+  pipeline_test_shards:
+    steps:
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@6: {}
+    - cocoapods-install@2: {}
+    - git::https://github.com/DamienBitrise/bitrise-test-plan-sharder.git@master:
+        title: Bitrise Test Plan Sharder
+        inputs:
+        - xcode_project: Notes.xcodeproj
+        - target: NotesUITests
+        - shards: '5'
+        - scheme: Notes
+        - test_plan: Notes.xctestplan
+        - debug_mode: 'true'
+        - test_path: ''
+        - file_type: ".swift"
+    - script@1.1:
+        title: Build for Testing
+        inputs:
+        - content: |+
+            set -euxo pipefail
+            echo "-- build-for-testing --"
+
+            mkdir DerivedData
+
+            xcodebuild \
+            -scheme "Notes" \
+            -workspace "Notes.xcworkspace" \
+            -sdk iphonesimulator \
+            -destination "platform=iOS Simulator,name=iPhone 8,OS=latest" \
+            -derivedDataPath "${BITRISE_SOURCE_DIR}/DerivedData" \
+            build-for-testing
+
+    - script@1.1:
+        title: Compress Derived Data
+        is_always_run: true
+        inputs:
+        - content: |
+            set -euxo pipefail
+            echo "-- compress --"
+
+            exec zip -0 -qr \
+                "${BITRISE_SOURCE_DIR}/DerivedData.zip" \
+                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug-iphonesimulator/Notes.app" \
+                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug-iphonesimulator/NotesUITests-Runner.app" \
+                "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Notes_Notes_iphonesimulator13.5-x86_64.xctestrun" \
+                "$BITRISE_SOURCE_DIR/Notes.xcworkspace" \
+                "$BITRISE_SOURCE_DIR/Notes.xcodeproj" \
+                "$BITRISE_SOURCE_DIR/Notes.xctestplan" \
+                "$BITRISE_SOURCE_DIR/TestShard_0.xctestplan" \
+                "$BITRISE_SOURCE_DIR/TestShard_1.xctestplan" \
+                "$BITRISE_SOURCE_DIR/TestShard_2.xctestplan" \
+                "$BITRISE_SOURCE_DIR/TestShard_3.xctestplan" \
+                "$BITRISE_SOURCE_DIR/TestShard_4.xctestplan"
+    - deploy-to-bitrise-io@2:
+        inputs:
+        - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
     before_run: []
 app:
   envs:
